export {
  AnimationController,
  createAnimationController,
  createExpressionRenderHook,
  createLiveEditSession,
} from '../core/motion';
export type {
  AnimatableProperty,
  Animation,
  AnimationConfig,
  AnimationValues,
  Easing,
  Expression,
  ExpressionApplyResult,
  ExpressionAudioContext,
  ExpressionAudioProvider,
  ExpressionContext,
  ExpressionEvaluator,
  ExpressionHelpers,
  Keyframe,
  KeyframeConfig,
  LiveEditBindingOptions,
  LiveEditInput,
  LiveEditMode,
  LiveEditOptions,
  LiveEditParseMode,
  LiveEditSession,
  LiveEditSessionOptions,
  MotionTargetValues,
} from '../shared';
